### ISSUE TITLE
Add sustainability governance zones

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#1]
Governance zones control which assets are visible to particular people/processes.  The `sustainability` governance zone will be used to tag data sets that are useful to the sustainability initiative.   When the team building the sustainability database issue a query to find out which data set are available, they will only see the data set that are tagged with this zone.

This task creates a sample that adds the definition of the new governance zone called "sustainability" to Egeria.  

It is only possible to add this definition once so the sample should begin by retrieving the existing governance zones and checking to see if the sustainability governance zone is already created.  If it is then delete it.  Then adding the new governance zone definition for sustainability and finally retrieve and print out all of the defined governance zones to show the new definition in the list.

If you are looking for a follow on piece of work, issue #14 works with the sustainability zone.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/governance-program/sustainability-governance-zone
