### ISSUE TITLE
List data centres, their systems and where they are located

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#10]
This task builds a sample report that lists the data centres that Coco Pharmaceuticals offers and the site location of each data centre.   It then shows how to catalog the IT systems in a data centre and link them to the data centre.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored:

https://github.com/odpi/egeria-samples-api/tree/main/operations-inventory/list-systems-locations
