### ISSUE TITLE
Build and catalog a reference data mapping table

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#11]
Data that comes from different sources often makes use of different units and names for the same concept.  It is important to know which names are equivalent to one another, if data that is using the different names is to be combined.

Egeria provides the capability to maintain lists of values (called Valid Value Sets).  This lists can then be mapped together to show the values that have the same meaning.  With this type of mapping the data pipelines can accurately and consistently translate between the values used in different sources.

This task is to create one valid value set of common names for polutants, and another with these polutant's scientific name.  Then map the equivant common name to its scientific name.  This will allow data sets that use the common names to be combined with data sets that use the scientific names.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored:

https://github.com/odpi/egeria-samples-api/tree/main/cataloguing-data/reference-mapping

**Comment by isamatha** [comment]
Can you assign this issue me and @elizajanemc. We will be working on this together.

**Comment by planetf1** [comment]
@isamatha - I've assigned to you. I can add @elizajanemc if she comments on the issue first (github requires this)

**Comment by elizajanemc** [comment]
Hi! please assign task to me as well. Thanks!

**Comment by mandy-chessell** [comment]
Consider the [ReferenceDataManager](https://odpi.github.io/egeria/org/odpi/openmetadata/accessservices/digitalarchitecture/client/ReferenceDataManager.html) client.

**Comment by elizajanemc** [comment]
Is the goal to take the values in csv file and add to the project image?

**Comment by mandy-chessell** [comment]
Yes :)
