### ISSUE TITLE
Add the facilities at the new Bucharest site

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#12]
Coco Pharmaceuticals has just acquired a new advanced manufacturing site in Bucharest which specialises in small batch manufacturing of pharmaceutical product.

This task adds details of the facilities to Coco Pharmaceuticals' operations inventory so that they can begin to account for the site's sustainability.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/operations-inventory/add-new-site
