### ISSUE TITLE
Catalog a utility bill for sustainability analysis

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#13]
Sustainability reporting includes providing information about the organization's power use.  One source of information is the electricity and gas utility bills that record the amount of power that is being purchased from the utility companies.

This information can be extracted from the company ledgers that record the payments made by the company.  This task builds a sample that shows how to catalog the company ledger systems to identify where the utility bill information is located.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/cataloguing-data/utility-bill
