### ISSUE TITLE
List the data sets available for sustainability analysis

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#14]
Governance zones are used to group data set together that are being used for a particular project or other activity.  This example creates a python script that makes calls to Egeria to list the data sets that are tagged as belonging to the "sustainability" governance zone.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/sustainability-dashboard/data-sets-for-analysis
