### ISSUE TITLE
Create data pipeline for sustainability dashboard

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#15]
A data pipeline is responsible for copying, transforming and combining data so it is stored in a convenient location and format for new processes, such as analytics, and reports.

This task creates a python script to simulate the copying of data from some of Coco Pharmaceuticals systems, combining them together and storing the results in a database table for the sustainability dashboard.  It adds the lineage of this simulated pipeline to Egeria.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/sustainability-dashboard/create-data-pipeline
