### ISSUE TITLE
Add lineage for sustainability data pipelines

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#16]
Lineage shows the flow of data between IT systems.  It is important to show the dependencies between systems and to demonstrate that the data used in a dashboard/report has come from appropriate data sources.

Create a sample program that adds the lineage releationships to Egeria to describe how data is flowing to the sustainability dashboard.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/sustainability-dashboard/lineage-data-pipelines
