### ISSUE TITLE
List the IT systems used by each business area and their power use

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#17]
Business leaders across Coco Pharmaceuticals need to to look at their use of IT to determine if there are savings/optimizations to be made.  Typically they do not know how many IT systems are supporting their area of the business.  

Create a report that lists the IT systems with a short description, their type, location and power use.  This type of report helps to educate the business leaders on their use of IT.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/it-systems/list-power-use
