### ISSUE TITLE
List IT systems with no lineage

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#18]
Lineage shows how data flows between IT systems.  It is very unusual for an IT system to be completely isolated, identifying the systems that have no lineage relationships may identify:

* IT systems that are not used any more
* IT systems that have not had their lineage defined

This sample creates a list of IT systems with no lineage defined so that the IT team can investigate them further.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/it-systems/list-no-lineage
