### ISSUE TITLE
Add sustainability governance domain

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#2]
Sustainability is a new focus area for Coco Pharmaceuticals that involves all aspects of its operation.  Such focus areas are managed as a governance domain.  Each domain defines processes and roles to coordinate the different parts of the business to achieve a broad goal.

This task adds the definition of the new sustainability governance domain to Egeria with the following values:

* domainIdentifier = 9
* displayName = "Sustainability"
* description = "Ongoing improvement in sustainability of operation through better use of resources."

**Instructions**

Begin by locating the governance domain set called "GovernanceDomainSet:CocoPharmaceuticals".  This will return details about the governance domain set itself and the list of existing governance domains.

Once you have the unique identfier (GUID) for the goverance domain set then add the new governance domain.

Then retrieve "CocoPharmaceuticals:GovernanceDomainSet" again and check that the new sustainability domain has been added.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/governance-program/sustainability-governance-domain
