### ISSUE TITLE
Identify the business areas of the frequent travellers

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#20]
Some travel is unavoidable.  However, it is an area where Coco Pharmaceuticals should look to ensure their business travel is appropriate.  Coco Pharmaceuticals has been focusing on employee expenses to determine the amount of travel.  The data sets 

This task creates a lookup table that maps employees to their business capabilities.  This will be used in highlighting the amount of business travel that employees of each business area are undertaking in the sustainability dashboard.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/cataloguing-data/areas-frequent-travellers
