### ISSUE TITLE
List the locations of the factories at Coco Pharmaceuticals

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#21]
Inside Egeria are details of all of the facilities at each of the sites that Coco Pharmaceuticals operates.  This task creates a list of all of the Coco Pharmaceutical sites that have a manufacturing facility (factory).

**Comment by ellapreedy** [comment]
The link to where the sample should be stored:

https://github.com/odpi/egeria-samples-api/tree/main/operations-inventory/list-locations
