### ISSUE TITLE
Add a Todo for each facility leader to create an inventory of their equipment

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#22]
Coco Pharmaceuticals does not keep a centralized list of the equipment they run at each of their facilities.  It is up to the facility leader to manage the purchasing, maintenance and repair of their local equipment.  The sustainability initiative needs a complete inventory of their equipment.

This task creates a sample to show how to look up each facility leader and assign them a ToDo to request that they create a list of their local equipment.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored:

https://github.com/odpi/egeria-samples-api/tree/main/operations-inventory/inventory-to-do
