### ISSUE TITLE
Create the sustainability initiative's projects and tasks

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#23]
Coco Pharmaceuticals need to coordinate a lot of different activity to get their sustainability initiative off of the ground.

This task creates a sample to set up the description of the projects associated with the sustainability and the key tasks involved.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/governance-program/sustainability-project
