### ISSUE TITLE
Catalog the IT systems at the London data centre

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#24]
One of [Gary Geeke's](https://egeria-project.org/practices/coco-pharmaceuticals/personas/gary-geeke/) team has created a spreadsheet of the IT systems in their London data centre.

This task is to catalog these systems and link them to the London data centre facility.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/it-systems/catalogue-it-systems
