### ISSUE TITLE
Appoint Tom Tally as the sustainability leader

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#25]
The sustainability governance domain is lead by the sustainability governance officer.  Locate the definition of the sustainability governance officer role and appoint [Tom Tally](/https://egeria-project.org/practices/coco-pharmaceuticals/personas/tom-tally/) to this role.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/governance-program/sustainability-leader
