### ISSUE TITLE
Create an email distribution list for the sustainability governance team

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#26]
Tom Tally, the leader of the sustainability initiative, wants to send emails to the rest of the sustainability governance team.  This task is to complete the sample that locates the sustainability governance roles and for each locate the people appointed to this role and for each, extract their work email and by this process, build up a table of roles, names and email addresses for the whole team.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/governance-program/sustainability-team-emails
