### ISSUE TITLE
Create governance metric definitions for sustainability

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#27]
Governance metrics define the values that need to be measured and the targets that the organization is striving to achieve. This task builds a sample that shows how to define a governance metric.

This sample can be run multiple times, so it begins by deleting the elements it plans to create if they are already defined in the metadata server.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored:

https://github.com/odpi/egeria-samples-api/tree/main/governance-program/sustainability-metrics
