### ISSUE TITLE
List the number of aspects that are set up for sustainability so far

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#28]
The other samples in this repository are setting up different parts of the governance program. This task creates a sample that queries Egeria and indicates which parts are set up and which are yet to complete.  As the samples are completed, this sample will return more information.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/governance-program/sustainability-aspects
