### ISSUE TITLE
Create a sustainability community

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#30]
Governance, such as managing the sustainability of an operation, typically involves people from across the organization.
The traditional team (department) structure is designed to organize people for the every-day work of the business.

This task builds a sample that creates a community for people involved in the sustainability initiative. The community is used to provide education and other information that is useful to people working on sustainability at Coco Pharmaceuticals.  Communities also serve as the backbone for formal and informal collaborations between individuals and teams across the company.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored:

https://github.com/odpi/egeria-samples-api/tree/main/governance-program/sustainability-community
