### ISSUE TITLE
Create new metadata server for the sustainability initiative

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#31]
Tom Tally is new to working with metadata, and she is keen to experiment. She asks Gary Geeke to set up a test metadata server with some sample metadata in it.

This task creates a sample that shows how to define a new metadata server for testing. It loads an open metadata archive with metadata from Coco Pharmaceuticals.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored:

https://github.com/odpi/egeria-samples-api/tree/main/governance-program/sustainability-metadata-server
