### ISSUE TITLE
Identify the number of people at each location

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#32]
Emissions produced in an office environment are primarily driven by the number of people at work, which also often correlates with the size of the office space. More people means more heating and cooling, often over a larger area. This information is combined with power consumption information to help us calculate and analyze Scope 2 emissions.

This task builds a sample that creates a report showing the number of people at each location.  It can be run multiple times, so it begins by deleting the elements it plans to create if they are already defined in the metadata server.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/governance-program/people-at-locations
