### ISSUE TITLE
Create a Valid Value Set for coolant types

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#35]
Coco Pharmaceuticals need to create an inventory of their refrigeration unit with the type of coolant they use.  
The aim is to replace each refrigeration unit that uses CFCs or HCFCs since
these are ozone depleting chemicals.

A valid value set defines a list of the possible values for a property.
Coco Pharmaceuticals want a valid value set for the different types of coolant they use.
This can be used to validate the coolant information in the inventory
and to act as dropdowns in their sustainability dashboard.

## Building the valid value set

Use the information on this web page [https://airconditionerlab.com/ac-refrigerant-types/](https://airconditionerlab.com/ac-refrigerant-types/) to extract the different types, with their descriptions and add them to a valid value set.

## Additional exercise

Add an external reference to the valid value set to record the link to the web page used to provide the valid values.
This external reference link shows the provenance of the information used to build the valid value list so that
it can be checked and validated as accurate.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/operations-inventory/coolant-types

**Comment by mandy-chessell** [comment]
**API Recommendations**

Consider using the [ValidValueManagement](https://odpi.github.io/egeria/org/odpi/openmetadata/accessservices/datamanager/client/ValidValueManagement.html) client of the Data Manager OMAS to create your valid value set.

Similarly, the [ExternalReferenceManagement](https://odpi.github.io/egeria/org/odpi/openmetadata/accessservices/datamanager/client/ExternalReferenceManagerClient.html) can be used to set up the external reference.
