### ISSUE TITLE
Add sustainability subject area definition

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#4]
When Coco Pharmaceuticals began their sustainability initiative they came across many new terms, code values, rules and calculations. A *Subject Area* describes a topic of interest.  It is used to group definitions about that topic area together.

This task creates a sample that shows how to create a subject area definition for sustainability.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/governance-program/sustainability-subject-area
