### ISSUE TITLE
Add sustainability glossary definitions

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#5]
The sustainability initiative introduced a lot of new terminology to the people at Coco Pharmaceuticals.  They created a glossary that could be used to help educate people on the meanings of these terms and also to link them to the data sets and other implementations to show where the concepts and data behind these terms are used.

This task creates a sample to show how to create a glossary of terms and retrieve specific terms from Egeria.  It needs to be able to run multiple times and so it fisrt checks the terms are not created already and deleted them if there are present.  After that it defines the terms and illustrates how to retreive on of them using a search command.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/governance-program/sustainability-glossary
