### ISSUE TITLE
Create new types to catalog refrigeration units

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#7]
There are over 600 types defined in the [open metadata type system](https://egeria-project.org/types/) that cover many of the types of information that you would want to store in Egeria.  Nevertheless, the type system is extensible so you can add new types to store information about anything.

In this task you will be writing a sample to create a new type to store information about refrigeration units.  These types are defined in an [open metadata archive](https://egeria-project.org/concepts/open-metadata-archive) that can be loaded into any open metadata server.  Once they are loaded, you can create instances of these types.  The sample also shows how to use the Open Metadata Store Client to create, update and delete elements of this new type.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/operations-inventory/refrigeration-unit-types
