### ISSUE TITLE
Map reference data between GHG protocol and Coco Pharmaceuticals reference data

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-samples-api#8]
The Greenhouse Gas (GHG) protocol provides a spreadsheet to perform the emissions calculations.  The data from the organization has to be transformed into the right format before adding to the spreadsheet.  One type of transformations required is to map code values and units (reference data) to the values needed in the spreadsheet.

This task creates a reference data mapping table in Egeria for use by the data pipeline that prepares the data for the spreadsheet.  This involves creating a valid value set for each of the internal formats and one for the GHG protocol values and then map them together.  The sample then demonstrates how to use Egeria to take a value from one valid value set and retrieve the equivalent value from another.

**Comment by ellapreedy** [comment]
The link to where the sample should be stored: 

https://github.com/odpi/egeria-samples-api/tree/main/cataloguing-data/map-data-GHG
